export const countryCurrencyMap: Record<
	string,
	{ code: string; symbol: string }
> = {
	'United States': { code: 'USD', symbol: '$' },
	Canada: { code: 'CAD', symbol: 'CA$' },
	'United Kingdom': { code: 'GBP', symbol: '£' },
	Australia: { code: 'AUD', symbol: 'A$' },
	Germany: { code: 'EUR', symbol: '€' },
	France: { code: 'EUR', symbol: '€' },
	Spain: { code: 'EUR', symbol: '€' },
	Italy: { code: 'EUR', symbol: '€' },
	Japan: { code: 'JPY', symbol: '¥' },
	China: { code: 'CNY', symbol: '¥' },
	India: { code: 'INR', symbol: '₹' },
	Brazil: { code: 'BRL', symbol: 'R$' },
	Mexico: { code: 'MXN', symbol: 'MX$' },
	'South Africa': { code: 'ZAR', symbol: 'R' },
	Nigeria: { code: 'NGN', symbol: '₦' },
	Egypt: { code: 'EGP', symbol: 'E£' },
	Russia: { code: 'RUB', symbol: '₽' },
	Turkey: { code: 'TRY', symbol: '₺' },
	Argentina: { code: 'ARS', symbol: '$' },
	Colombia: { code: 'COP', symbol: '$' },
	Indonesia: { code: 'IDR', symbol: 'Rp' },
	Pakistan: { code: 'PKR', symbol: '₨' },
	Bangladesh: { code: 'BDT', symbol: '৳' },
	Philippines: { code: 'PHP', symbol: '₱' },
	Vietnam: { code: 'VND', symbol: '₫' },
	Thailand: { code: 'THB', symbol: '฿' },
	Malaysia: { code: 'MYR', symbol: 'RM' },
	Singapore: { code: 'SGD', symbol: 'S$' },
	'South Korea': { code: 'KRW', symbol: '₩' },
	'Saudi Arabia': { code: 'SAR', symbol: '﷼' },
	'United Arab Emirates': { code: 'AED', symbol: 'د.إ' },
	Netherlands: { code: 'EUR', symbol: '€' },
	Sweden: { code: 'SEK', symbol: 'kr' },
	Norway: { code: 'NOK', symbol: 'kr' },
	Denmark: { code: 'DKK', symbol: 'kr' },
	Finland: { code: 'EUR', symbol: '€' },
	Poland: { code: 'PLN', symbol: 'zł' },
	Switzerland: { code: 'CHF', symbol: 'Fr' },
	Austria: { code: 'EUR', symbol: '€' },
	Belgium: { code: 'EUR', symbol: '€' },
	Ireland: { code: 'EUR', symbol: '€' },
	Portugal: { code: 'EUR', symbol: '€' },
	Greece: { code: 'EUR', symbol: '€' },
	'Czech Republic': { code: 'CZK', symbol: 'Kč' },
	Hungary: { code: 'HUF', symbol: 'Ft' },
	Romania: { code: 'RON', symbol: 'lei' },
	Ukraine: { code: 'UAH', symbol: '₴' },
	Chile: { code: 'CLP', symbol: '$' },
	Peru: { code: 'PEN', symbol: 'S/' },
	'New Zealand': { code: 'NZD', symbol: 'NZ$' },
	Morocco: { code: 'MAD', symbol: 'د.م.' },
	Kenya: { code: 'KES', symbol: 'KSh' },
	Ghana: { code: 'GHS', symbol: '₵' },
	Other: { code: 'USD', symbol: '$' },
};

export function getCurrencyByCountry(country: string) {
	return countryCurrencyMap[country] || countryCurrencyMap['Other'];
}
